name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ 3.11 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Set up
        env:
          DB_ENGINE: django.db.backends.mysql
          DB_NAME: portfolio_db
          DB_NAME_TEST: test_portfolio_db
          DB_USER: root
          DB_USER_PYTHON: python
          DB_PASSWORD: root
          DB_PASSWORD_PYTHON: password
        run: |
          sudo systemctl start mysql
          mysql -u$DB_USER -p$DB_PASSWORD -e "CREATE USER '$DB_USER_PYTHON'@'localhost' IDENTIFIED BY '$DB_PASSWORD_PYTHON';"
          mysql -u$DB_USER -p$DB_PASSWORD -e "GRANT CREATE, DROP, SELECT, UPDATE, INSERT, DELETE, ALTER, REFERENCES, INDEX on $DB_NAME.* to '$DB_USER_PYTHON'@'localhost';"
          mysql -u$DB_USER -p$DB_PASSWORD -e "GRANT CREATE, DROP, SELECT, UPDATE, INSERT, DELETE, ALTER, REFERENCES, INDEX on $DB_NAME_TEST.* to '$DB_USER_PYTHON'@'localhost';"
          mysql -u$DB_USER_PYTHON -p$DB_PASSWORD_PYTHON -e "CREATE DATABASE $DB_NAME DEFAULT CHARACTER SET utf8mb4;"
          python3 --version
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python manage.py makemigrations register
          python manage.py migrate
          python manage.py makemigrations vietnam_research gmarker shopping linebot warehouse
          python manage.py migrate
          export DJANGO_SECRET_KEY="$(base64 <<< "$RANDOM|TeStiNg|$RANDOM" | tr -d '\n')"

      - name: Check Tables and Permissions
        env:
          DB_NAME: portfolio_db
          DB_USER: root
          DB_USER_PYTHON: python
          DB_PASSWORD: root
          DB_PASSWORD_PYTHON: password
        run: |
          echo "Checking DB tables..."
          mysql -u$DB_USER_PYTHON -p$DB_PASSWORD_PYTHON -e "USE $DB_NAME; SHOW TABLES;"
          echo "Checking user permissions..."
          mysql -u$DB_USER -p$DB_PASSWORD -e "SHOW GRANTS FOR '$DB_USER_PYTHON'@'localhost';"

      - name: Run tests
        env:
          DB_ENGINE: django.db.backends.mysql
          DB_NAME: portfolio_db
          DB_NAME_TEST: test_portfolio_db
          DB_USER: root
          DB_USER_PYTHON: python
          DB_PASSWORD: root
          DB_PASSWORD_PYTHON: password
        run: |
          source venv/bin/activate
          python manage.py test
